### ISSUE TITLE
Getting Error karma.conf.js does not exist!

### ISSUE THREAD

**Issue by joelmuskwe** [davinkevin/jest#1]
Angular CLI: 6.1.4
Node: 8.11.3
Angular: 6.1.3

```
ng test
21 08 2018 13:53:05.428:ERROR [config]: File /Users/joelmuskwe/Joel/projects/examples/ng-tests/src/karma.conf.js does not exist!
```

**Comment by davinkevin** [comment]
That was an error from my side on the documentation.

Currently, to launch test you have to execute `npm run test` or `npm run test:watch`. You also can do this with `yarn`

I hope I helped you 😊

You can close the issue if it's ok for you.

**Comment by joelmuskwe** [comment]
couldn't test tried creating new project but getting same error as #2

**Comment by davinkevin** [comment]
Closed too ?

**Comment by joelmuskwe** [comment]
everything working thank you
